DELETE FROM TIC_COMPILACIONES_MASIVA;
DELETE FROM DES_GRUPO_FUNCIONAL;
DELETE FROM DES_PAQUETES;
DELETE FROM DES_GRUPOS_FUNC_PAQUETE;
DELETE FROM TIC_PAQUETES_ENTIDAD;
DELETE FROM TIC_GRUPOS_FUNC_ENTIDAD;

INSERT INTO TIC_COMPILACIONES_MASIVA (ENTIDAD,ENTORNO,NOMBRE_GRUPO_FUNCIONAL,COMP_FULL_CHEK_SN,FECHA_HORA_PETICION,FECHA_HORA_ULTIMO_ESTADO,FICHERO_FUENTE,FUENTE,RESULTADO,RESULTADO_COMPILACION,REVISION,TIPO_FUENTE,TIPO_GRUPO_FUNCIONAL,USUARIO,VERSION) 
VALUES (9999,'PRODUCCIO','87LPR','S',{ts '2018-12-11 00:00:00'},{ts '2018-12-11 00:00:00'},null,'U87949',null,1,24,'COB',3,16518,3);
INSERT INTO TIC_COMPILACIONES_MASIVA (ENTIDAD,ENTORNO,NOMBRE_GRUPO_FUNCIONAL,COMP_FULL_CHEK_SN,FECHA_HORA_PETICION,FECHA_HORA_ULTIMO_ESTADO,FICHERO_FUENTE,FUENTE,RESULTADO,RESULTADO_COMPILACION,REVISION,TIPO_FUENTE,TIPO_GRUPO_FUNCIONAL,USUARIO,VERSION) 
VALUES (9999,'ETIC','81TAL','S',{ts '2017-03-24 00:00:00'},{ts '2017-03-24 00:00:00'},null,'D00243',null,2,0,'COB',3,13249,1);
INSERT INTO TIC_COMPILACIONES_MASIVA (ENTIDAD,ENTORNO,NOMBRE_GRUPO_FUNCIONAL,COMP_FULL_CHEK_SN,FECHA_HORA_PETICION,FECHA_HORA_ULTIMO_ESTADO,FICHERO_FUENTE,FUENTE,RESULTADO,RESULTADO_COMPILACION,REVISION,TIPO_FUENTE,TIPO_GRUPO_FUNCIONAL,USUARIO,VERSION) 
VALUES (9999,'PRODUCCIO','85TRAS','S',{ts '2017-03-31 00:00:00'},{ts '2017-03-31 00:00:00'},null,'S85890',null,2,1,'COB',3,13249,5);
INSERT INTO TIC_COMPILACIONES_MASIVA (ENTIDAD,ENTORNO,NOMBRE_GRUPO_FUNCIONAL,COMP_FULL_CHEK_SN,FECHA_HORA_PETICION,FECHA_HORA_ULTIMO_ESTADO,FICHERO_FUENTE,FUENTE,RESULTADO,RESULTADO_COMPILACION,REVISION,TIPO_FUENTE,TIPO_GRUPO_FUNCIONAL,USUARIO,VERSION) 
VALUES (9999,'PRODUCCIO','V87859','S',{ts '2019-03-20 00:00:00'},{ts '2019-03-20 00:00:00'},null,'V87859',null,2,20,'COB',2,16216,1);

INSERT INTO DES_GRUPO_FUNCIONAL (NOMBRE_GRUPO_FUNCIONAL,TIPO_GRUPO_FUNCIONAL,APLICACION,TEMA,FECHA_ALTA,FECHA_BAJA,USUARIO_ALTA,USUARIO_BAJA,GRUPO_DESARROLLO,MODIFICABLE_SN,CORRECCION_ERROR_SN,DESCRIPCION,IDDESCRIPCION,FORMATO_MENSAJE,USUARIO_CKOUT,FECHA_CKOUT,DOMINIO_AYUDAS) 
VALUES ('81TAL',3,'EXPLO','ETIC-ADMIN',{ts '2008-10-06 00:00:00'},null,2147,null,'Cobol eTic','S','N','MANTENIMENT A/B/M TIC_TIPOS_GRUPO_FUNCIONAL',3870,0,null,null,'ET');
INSERT INTO DES_GRUPO_FUNCIONAL (NOMBRE_GRUPO_FUNCIONAL,TIPO_GRUPO_FUNCIONAL,APLICACION,TEMA,FECHA_ALTA,FECHA_BAJA,USUARIO_ALTA,USUARIO_BAJA,GRUPO_DESARROLLO,MODIFICABLE_SN,CORRECCION_ERROR_SN,DESCRIPCION,IDDESCRIPCION,FORMATO_MENSAJE,USUARIO_CKOUT,FECHA_CKOUT,DOMINIO_AYUDAS) 
VALUES ('85TRAS',3,'GESTIO','ETIC-ADMIN',{ts '2008-10-06 00:00:00'},null,2147,null,'Cobol eTic','S','N','MENU ADMINISTRACIO ESTRUCTURA TIC2',3897,0,999999,{ts '2017-03-13 00:00:00'},'ET');
INSERT INTO DES_GRUPO_FUNCIONAL (NOMBRE_GRUPO_FUNCIONAL,TIPO_GRUPO_FUNCIONAL,APLICACION,TEMA,FECHA_ALTA,FECHA_BAJA,USUARIO_ALTA,USUARIO_BAJA,GRUPO_DESARROLLO,MODIFICABLE_SN,CORRECCION_ERROR_SN,DESCRIPCION,IDDESCRIPCION,FORMATO_MENSAJE,USUARIO_CKOUT,FECHA_CKOUT,DOMINIO_AYUDAS) 
VALUES ('V87859',3,'EXPLO','ETIC-ADMIN',{ts '2008-10-06 00:00:00'},null,2147,null,'Cobol eTic','S','N','MANTENIMENT A/B/M TIC_TIPOS_MAQUINA',3881,0,null,null,'ET');

