--DROP TABLE NO CORRECTE AQUI
--------------------------------------------------------
--  DDL for Table TIC_COMPILACIONES
--------------------------------------------------------
DROP TABLE TIC_COMPILACIONES IF EXISTS;
  CREATE TABLE TIC_COMPILACIONES 
   (	ENTIDAD NUMBER(4,0), 
	ENTORNO VARCHAR2(15 BYTE), 
	NOMBRE_GRUPO_FUNCIONAL VARCHAR2(32 BYTE), 
	USUARIO NUMBER(6,0), 
	TIPO_GRUPO_FUNCIONAL NUMBER(2,0), 
	VERSION NUMBER(4,0), 
	REVISION NUMBER(4,0), 
	FUENTE VARCHAR2(8 BYTE), 
	TIPO_FUENTE CHAR(3 BYTE), 
	FECHA_HORA_PETICION DATE, 
	RESULTADO_COMPILACION NUMBER(2,0), 
	FECHA_HORA_ULTIMO_ESTADO DATE, 
	FICHERO_FUENTE BLOB, 
	RESULTADO BLOB, 
	COMP_FULL_CHEK_SN CHAR(1 BYTE)
   ); --SEGMENT CREATION IMMEDIATE   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255  NOCOMPRESS LOGGING  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  
  --------------------------------------------------------
--  DDL for Table TIC_COMPILACIONES_MASIVA
--------------------------------------------------------
DROP TABLE TIC_COMPILACIONES_MASIVA IF EXISTS;
CREATE TABLE TIC_COMPILACIONES_MASIVA 
   (	ENTIDAD NUMBER(4,0), 
	ENTORNO VARCHAR2(15 BYTE), 
	NOMBRE_GRUPO_FUNCIONAL VARCHAR2(32 BYTE), 
	USUARIO NUMBER(6,0), 
	TIPO_GRUPO_FUNCIONAL NUMBER(2,0), 
	VERSION NUMBER(4,0), 
	REVISION NUMBER(4,0), 
	FUENTE VARCHAR2(8 BYTE), 
	TIPO_FUENTE CHAR(3 BYTE), 
	FECHA_HORA_PETICION DATE, 
	RESULTADO_COMPILACION NUMBER(2,0), 
	FECHA_HORA_ULTIMO_ESTADO DATE, 
	FICHERO_FUENTE BLOB, 
	RESULTADO BLOB, 
	COMP_FULL_CHEK_SN CHAR(1 BYTE), 
	PAQUETE NUMBER(10,0)
   ); --SEGMENT CREATION IMMEDIATE   PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255  NOCOMPRESS LOGGING  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  
   DROP TABLE DES_GRUPO_FUNCIONAL IF EXISTS;
   CREATE TABLE DES_GRUPO_FUNCIONAL 
   (	NOMBRE_GRUPO_FUNCIONAL VARCHAR2(32 BYTE), 
	TIPO_GRUPO_FUNCIONAL NUMBER(2,0), 
	APLICACION VARCHAR2(10 BYTE), 
	TEMA VARCHAR2(10 BYTE), 
	FECHA_ALTA DATE, 
	FECHA_BAJA DATE, 
	USUARIO_ALTA NUMBER(6,0), 
	USUARIO_BAJA NUMBER(6,0), 
	GRUPO_DESARROLLO VARCHAR2(20 BYTE), 
	MODIFICABLE_SN CHAR(1 BYTE), 
	CORRECCION_ERROR_SN CHAR(1 BYTE), 
	DESCRIPCION VARCHAR2(100 BYTE), 
	IDDESCRIPCION NUMBER(18,0), 
	FORMATO_MENSAJE NUMBER(2,0), 
	USUARIO_CKOUT NUMBER(6,0), 
	FECHA_CKOUT DATE, 
	DOMINIO_AYUDAS VARCHAR2(20 BYTE)
   ) ;
   
   DROP TABLE TIC_FUENTES_ENTORNOS IF EXISTS;
   CREATE TABLE TIC_FUENTES_ENTORNOS
(
   ENTIDAD decimal(4,0),
   ENTORNO varchar2(15),
   NOMBRE_GRUPO_FUNCIONAL varchar2(32),
   ESTADO_COMPILACION char(1),
   FECHA_COMPILACION timestamp,
   ESQUEMA varchar2(10),
   FUENTE_CBL blob,
   OPCIONES_COMPILACION decimal(2,0),
   XA_ASN char(1),
   FUENTE varchar2(8),
   TIPO_FUENTE varchar2(3),
   GENERICO_SN char(1),
   TRASPASABLE_SN char(1) DEFAULT 'S',
   VERSION_COMPILACION decimal(4,0),
   REVISION_COMPILACION decimal(4,0)
)
;

   
  CREATE SEQUENCE SEQ_PAQUETES START WITH 1 INCREMENT BY 1 NOCYCLE;